# Generated by Django 5.2.5 on 2025-08-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_tag_blogs_author_blogs_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.BooleanField(default=False),
        ),
    ]
