# Generated by Django 5.2.5 on 2025-09-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_caption_tag_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Caption',
            new_name='caption',
        ),
    ]
