# Generated by Django 5.2.5 on 2025-08-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_tag_alter_blogs_options_alter_blogs_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='tags',
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
