# Generated by Django 5.2.5 on 2025-08-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
