# Generated by Django 5.2.5 on 2025-09-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='caption',
            new_name='Caption',
        ),
    ]
